server:
  port: 8761
spring:
  config:
    activate:
      on-profile: server1
  application:
    name: EurekaServer
eureka:
  instance:
    hostname: 20.189.79.251
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
#---
#server:
#  port: 8762
#spring:
#  config:
#    activate:
#      on-profile: server2
#  application:
#    name: EurekaServer
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
