FROM maven:3.8.4-openjdk-17 AS build

EXPOSE 8888
WORKDIR /app

COPY . /app
RUN mvn package

FROM openjdk:17-alpine
WORKDIR /app

COPY --from=build /app/target/ConfigService-0.0.1-SNAPSHOT.jar ConfigService-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "ConfigService-0.0.1-SNAPSHOT.jar"]
