server:
  port: 8585

eureka:
  client:
    service-url:
      defaultZone: http://20.189.79.251:8761/eureka/

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/report/**, /csv/**