management:
    endpoint:
        health:
            show-details: always
    health:
        defaults:
            enabled: true
        mongo:
            enabled: true

    endpoints:
        web:
            exposure:
                include:
                    - '*'
server:
    port: ${PORT:8787}
    forward-headers-strategy: native
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://20.189.79.251:8761/eureka/
    instance:
        hostname: cs590priusreportservice.azurewebsites.net
spring:
    application:
        name: reporting-service
    cloud:
        config:
            allow-override: false
            discovery:
                enabled: true
            enabled: true
            name: reporting-service-from-server
            uri: http://20.189.79.251:8888/
    config:
        import: optional:configserver:http://20.189.79.251:8888/

app:
    topic:
        name:
            test: SS_2_1

kafka:
    topics:
        reporting:
            nsi-pattern: SS.*
#            nsi-pattern: RS.*
